services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: flight-dev
      POSTGRES_USER: flight-dev
      POSTGRES_PASSWORD: CLI-825.2025X
    ports:
      - "35001:5432"

volumes:
  flight-db:
    driver: local
