spring:
  application:
    name: flight-be
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: 'dev'  # Change to 'prod' for production deployment
  jpa:
    hibernate:
      ddl-auto: create-drop
