spring:
  application:
    name: flight-be
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: 'dev'  # Change to 'prod' for production deployment
  jpa:
    hibernate:
      ddl-auto: create-drop

# External services configuration
profile:
  service:
    base-url: ${PROFILE_SERVICE_BASE_URL:http://2306219575-be.hafizmuh.site}

# Service callback configuration for payment confirmation
service:
  callback:
    base-url:
      flight: ${FLIGHT_SERVICE_CALLBACK_BASE_URL:http://2306211660-be.hafizmuh.site}
      tourpackage: ${TOURPACKAGE_SERVICE_CALLBACK_BASE_URL:http://2306219575-be.hafizmuh.site}
      accommodation: ${ACCOMMODATION_SERVICE_CALLBACK_BASE_URL:http://2306212083-be.hafizmuh.site}
      vehiclerental: ${VEHICLERENTAL_SERVICE_CALLBACK_BASE_URL:http://2306203236-be.hafizmuh.site}
      insurance: ${INSURANCE_SERVICE_CALLBACK_BASE_URL:http://2306240061-be.hafizmuh.site}
